---
날짜: "2025-01-31"
넘버: 
태그: 프로그래밍/임베디드
출처: LIG Nex1 The SSEN Embedded SW School
강사: 김유진
aliases:
---
### 날짜:  2025-01-31 09:02

### 태그: #프로그래밍/임베디드

>[!메모]
>

### 원문
---
# 5.9 예외처리
- 컴파일 에러는 고마운 에러다.
- 런타임 에러로 프로그램이 종료되는 것은 치명적이다.
	- 사용자 경험 상으로도 좋지 않다.
	- 에러가 발생했음을 알리고 프로그램이 지속되도록 하는 것이 좋다.
- 3가지 키워드
	- try/catch/throw
- if 문을 이용한 예외처리
	- 예외처리 부분과 일반적인 프로그램의 흐름을 구분하기 힘들다.
### try
- try 블럭 안에서 발생한 예외만 처리할 수 있다.
	- 관련있는 코드끼리 묶는 것이 일반적이다.
	- try 블럭에서는  throw를 통해 예외의 발생을 catch블럭으로 전달한다.
```C++
try {
	/* code */
	if (예외 발생 시)
		throw expn;
	/* code */	
} caatch (type exn) {
	/* 예외처리 */
}
```
- 예외가 가장 많이 발생하는 부분
	- 입출력
	- 메모리 할당
- **예외로 던질 수 있는 타입**
	- 사용자 정의 타입(클래스)
	- 정수 등
### catch
- try블럭에서 일어난, 같은 타입의 예외만 받을 수 있다.
	- 예외의 종류에 따라 처리하는 로직이 다를수 있으므로 다른 타입의 예외를 받는 catch 블럭을 연결할 수 있다. 
- catch 블럭에서 에러를 처리하는 것은 어렵다.
	- 에러를 즉각 수정하는 로직보다는 에러를 알리고 프로그램을 지속시키는 목적으로 사용된다.
### stack unwinding
- try 블럭 내부에서 호출된 함수가 예외를 발생시키는 경우.
	- 예외가 발생했을 때 예외 데이터가 catch 블럭을 만날 때까지 전달된다.
![[Excalidraw/LIG Nex1_embedded_C.md#^group=zKfhcR66fcdS59M1F_i11]]
- 모든 종류의 예외를 처리할 수 있는 catch
	- 앨립시스 노테이션`(...)`
```cpp
try {
	switch (x) {
	case 1:
		throw -1;
		break;
	case 2:
		...
	}
} catch (int exnp) {
	// int 예외 처리	
} catch (float exnp) {
	// float 예외 처리
} catch (...) {
	// 나머지 예외 처리
}
```
### throw 함수
- 함수에서 발생할 수 있는 예외를 명시적으로 나타낼 수 있다.
```c++
int throwError() throw (int, char) {
	/* code */
}
```
### 예외 클래스와 예외 객체
- 예외 객체
	- 예외가 발생했음을 알리는 객체
- 예외 클래스
	- 예외 객체를 생성하기 위해 정의된 클래스
- 예외 객체를 통해서 예외 발생에 대한 더 구체적인 정보를 전달할 수 있다.
- [ ] 예외 객체가 쌓인 스택 내부에서 생성했을 경우 어떻게 동작하는가?
	- 무조건 힙 아닌가??
### new에 의해 전달되는 예외
- bad_alloc
```cpp
try {
	while (true)
		int *mem = new int[10000][10000];
} catch (bad_alloc& bad) {
	cerr << "memory allocation error\n";
}
```


---
### 생각(파생된 질문/생각)

### 출처
- LIG Nex1 The SSEN Embedded SW School

### 연결 문서 (연결 이유)
